#通过配置文件设置环境配置
#spring:
#  profiles:
#    active: pro

spring:
  profiles:
    active: ${profile.activate}
---
# 产品模式
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80

---
# 测试模式
spring:
  config:
    activate:
      on-profile: test
server:
  port: 81

---
# 开发模式
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 82